version: '3.0'
services:
  postgres:
    image: postgres:13
    volumes:
      - /opt/url-shortener/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
  adminer:
    image: adminer:4.8.1
    ports:
      - 7777:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    restart: always
  application:
    image: vyivanov/url-shortener:0.0.11
    ports:
      - 80:9080
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - HASH_SALT=${HASH_SALT}
    depends_on:
      - postgres
    restart: always
