version: '3.0'
services:
  postgres:
    image: postgres:13
    volumes:
      - /opt/url-shortener/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd
      - POSTGRES_DB=shortener
    restart: always
  adminer:
    image: adminer:4.8.1
    ports:
      - 7777:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    restart: always
  application:
    image: vyivanov/url-shortener:latest
    ports:
      - 80:9080
    depends_on:
      - postgres
    restart: always
