version: '3.0'
services:
  storage:
    image: postgres:13
    volumes:
      - /opt/url-shortener/storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - back_adminer
      - back_application
    restart: always
  adminer:
    image: adminer:4.8.1
    depends_on:
      - storage
    networks:
      - back_adminer
      - front_adminer
    restart: always
  application:
    image: vyivanov/url-shortener:0.0.24
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - HASH_SALT=${HASH_SALT}
    depends_on:
      - storage
    networks:
      - back_application
      - front_application
    restart: always
  proxy:
    image: vyivanov/nginx-1.21.1
    ports:
      - 80:80
      - 443:443
      - 5000:5000
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - adminer
      - application
    networks:
      - front_adminer
      - front_application
    restart: always
networks:
  front_adminer:
    driver: bridge
  front_application:
    driver: bridge
  back_adminer:
    driver: bridge
  back_application:
    driver: bridge
